path: /home/luciano/Documentos/helmet_detection/helmetDetection/train_mini
train: images/train
val: images/train

# Classes
names:
  0: motorbike
  1: DHelmet
  2: DNoHelmet
  3: P1Helmet
  4: P1NoHelmet
  5: P2Helmet
  6: P2NoHelmet
  7: P0Helmet
  8: P0NoHelmet